[version]
major = 0
minor = 1
patch = 1

[core]
appName = "ignis-sandbox"

[renderer]
backend = "vulkan"
maxRenderGraphs = 16
maxRenderPassesInGraph = 16
maxTextures = 128
maxBuffers = 128

[asset]
path = "../sandbox/res"

[vulkan]
apiVersion = "v1.3"
extensions = ["VK_EXT_debug_utils"]
layers = ["VK_LAYER_KHRONOS_validation"]
